library:
  source-dirs:
  - src
  exposed-modules:
  - CF
  - MagicCP
dependencies:
- time
- syb
- template-haskell
- array
- text
- aeson
- base
- configurator
- curl-aeson
- directory
- filepath
- process
- text
- unix
- MagicHaskeller
name: MagicCP
