library:
  source-dirs:
  - src
  exposed-modules:
  - CF
  - MagicCP
dependencies:
- MagicHaskeller
- aeson
- array
- base
- bytestring
- configurator
- curl-aeson
- directory
- filepath
- http-conduit
- html-conduit
- process
- syb
- template-haskell
- time
- text
- text
- unix
- xml-conduit
name: MagicCP
